type = "program"
description = "draw all maxes at graphic with distance line"

[properties]
module = "file://localhost/$PWD/interpret_draw_all_maxes_at_square"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }

[[properties.languages]]
name = "python"
version = "3.10"
