type = "program"
description = "read traces"

[properties]
module = "file://localhost/$PWD/cube_get_cumsum"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }

[[properties.managers.package]]
provider = "pip"
dependencies = "file://localhost/$PWD/requirements.txt"

[[properties.languages]]
name = "python"
version = "3.10"
