type = "program"
description = "draw travel time at traces"

[properties]
module = "file://localhost/$PWD/interpret_draw_tt_at_traces"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }



[[properties.languages]]
name = "python"
version = "3.10"
