type = "program"
description = " "

[properties]
module = "file://localhost/$PWD/region_create_region"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }

[[properties.managers.package]]
provider = "pip"
dependencies = "file://localhost/$PWD/requirements.txt"

[[properties.languages]]
name = "python"
version = "3.10"
