type = "program"
description = "get cube"

[properties]
module = "file://localhost/$PWD/cube_get_cube"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }

[[properties.languages]]
name = "python"
version = "3.10"
