type = "program"
description = " "

[properties]
module = "file://localhost/$PWD/model_get_velmodel"
entrypoint = ["python", "main.py"]

[properties.managers]
environment = { provider = "miniconda", name = "microseismic" }

[[properties.languages]]
name = "python"
version = "3.10"
